"""Initial migration

Revision ID: 3bfdc44a03ee
Revises: 91dcbec4b756
Create Date: 2023-12-16 02:03:26.427161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bfdc44a03ee'
down_revision: Union[str, None] = '91dcbec4b756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('date_to', sa.Date(), nullable=False))
    op.drop_column('bookings', 'date_ro')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('date_ro', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('bookings', 'date_to')
    # ### end Alembic commands ###
