"""Initial migration

Revision ID: 877d4445507b
Revises: 3bfdc44a03ee
Create Date: 2023-12-16 02:08:43.336479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '877d4445507b'
down_revision: Union[str, None] = '3bfdc44a03ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('total_cost', sa.Integer(), sa.Computed('(date_to - date_from) * price', ), nullable=True))
    op.add_column('bookings', sa.Column('total_days', sa.Integer(), sa.Computed('(date_to - date_from)', ), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'total_days')
    op.drop_column('bookings', 'total_cost')
    # ### end Alembic commands ###
