"""Initial migration

Revision ID: 91dcbec4b756
Revises: 0cc03752867d
Create Date: 2023-12-16 02:02:45.380981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91dcbec4b756'
down_revision: Union[str, None] = '0cc03752867d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('rooms', 'discription')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('discription', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('rooms', 'description')
    # ### end Alembic commands ###
